# Generated by Django 3.2.10 on 2021-12-23 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('simple_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPage',
            new_name='Index',
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Index'},
        ),
    ]
