# Generated by Django 3.2.10 on 2021-12-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('simple_blog', '0002_auto_20211221_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeriesItem',
        ),
    ]
