# Generated by Django 3.2.10 on 2021-12-23 11:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Allow visitors to comments'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_scripts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_styles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_comments',
            field=models.BooleanField(default=True, help_text='Show all comments'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
